/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BEmojiPicker: typeof import('./app/components/global/BEmojiPicker.vue')['default']
    BIcon: typeof import('./app/components/global/BIcon.vue')['default']
    BVirtualVerticalList: typeof import('./app/components/global/BVirtualVerticalList.vue')['default']
  }
}
